### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/vrm-api-python-client#1]
- [ ] Update the code (if needed)
- [x] Update readme, saying we will we try to maintaince this
- [x] publish to pypi, and update readme
- [ ] add tests 
- [ ]  CI to run the tests
- [x] add "ease of contribution" badge to repo

**Comment by peterdudfield** [comment]
Lrt me know @mduffin95 if you are happy to do readme updates, and then I can deploy it to pypi

**Comment by mduffin95** [comment]
Yep happy to make those changes, I can do that this evening

**Comment by mduffin95** [comment]
@peterdudfield I've updated the README now. Due to the [existing package](https://pypi.org/project/vrmapi/) I think we'll need to rename this one though. I'm going to go with `ocf_vrmapi`.

Will get round to doing the other points on the list soon.

**Comment by peterdudfield** [comment]
Thank you. I'll get it on pypi

**Comment by peterdudfield** [comment]
Its now on pypi - https://pypi.org/project/ocf-vrmapi/. @mduffin95 you ok to update quartz-solar PR? https://pypi.org/project/ocf-vrmapi/

**Comment by mduffin95** [comment]
@peterdudfield that's done now
